{
parserClass="com.uncivildev.sliq.lang.core.parser.SliqParser"

implements="com.uncivildev.sliq.lang.core.psi.ext.SliqElement"

extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

elementTypeHolderClass="com.uncivildev.sliq.lang.core.psi.SliqTypes"
elementTypeClass="com.uncivildev.sliq.lang.core.psi.SliqElementType"
tokenTypeClass="com.uncivildev.sliq.lang.core.psi.SliqTokenType"

psiClassPrefix="Sliq"
psiImplClassSuffix="Impl"
psiPackage="com.uncivildev.sliq.lang.core.psi"
psiImplPackage="com.uncivildev.sliq.lang.core.psi.impl"
psiImplUtilClass="com.uncivildev.sliq.lang.core.psi.impl.SliqPsiImplUtil"

tokens = [
  // Delimiters
  LIQUID_TAG_BEGIN='regexp:\{%-?'
  LIQUID_TAG_END='regexp:-?%}'

  LIQUID_OUTPUT_START='regexp:\{\{-?'
  LIQUID_OUTPUT_END='regexp:-?}}'

  TAG_NAME_RAW='raw'
  TAG_NAME_ENDRAW='endraw'

  WHITE_SPACE='regexp:[ \n\r\t\f]+'

  RAW_TEXT='regexp:(.|[\n\r\t\f ])*'
  TEMPLATE_TEXT='regexp:.*'
]
}

sliqFile ::= core*

core ::= raw_tag {
  recoverWhile = recover_tag_end
}

raw_tag ::= raw_tag_begin raw_content* raw_tag_end? {
  pin = 1
}

raw_tag_begin ::= LIQUID_TAG_BEGIN TAG_NAME_RAW LIQUID_TAG_END {
  pin = 1
}

raw_tag_end ::= LIQUID_TAG_BEGIN TAG_NAME_ENDRAW LIQUID_TAG_END {
  pin = 1
}

raw_content ::= RAW_TEXT+

private recover_tag_end ::= !(LIQUID_TAG_BEGIN)