{
parserClass="com.uncivildev.shopifyliquid.language.parser.ShopifyLiquidParser"

extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

psiClassPrefix="ShopifyLiquid"
psiImplClassSuffix="Impl"
psiPackage="com.uncivildev.shopifyliquid.language.psi"
psiImplPackage="com.uncivildev.shopifyliquid.language.psi.impl"

elementTypeHolderClass="com.uncivildev.shopifyliquid.language.psi.ShopifyLiquidTypes"
elementTypeClass="com.uncivildev.shopifyliquid.language.psi.ShopifyLiquidElementType"
tokenTypeClass="com.uncivildev.shopifyliquid.language.psi.ShopifyLiquidTokenType"

psiImplUtilClass="com.uncivildev.shopifyliquid.language.psi.impl.ShopifyLiquidPsiImplUtil"

tokens = [
  // Delimiters
  LIQUID_TAG_START='{%'
  LIQUID_TAG_START_STRIP='{%-'
  LIQUID_TAG_END='%}'
  LIQUID_TAG_END_STRIP='-%}'
  LIQUID_OUTPUT_START='{{'
  LIQUID_OUTPUT_START_STRIP='{{-'
  LIQUID_OUTPUT_END='}}'
  LIQUID_OUTPUT_END_STRIP='-}}'

  // Keywords (Tags)
  ASSIGN='assign'
  BREAK='break'
  CAPTURE='capture'
  ENDCAPTURE='endcapture'
  CASE='case'
  ENDCASE='endcase'
  COMMENT='comment'
  ENDCOMMENT='endcomment'
  CONTINUE='continue'
  CYCLE='cycle'
  DECREMENT='decrement'
  ECHO='echo'
  ELSE='else'
  ELSIF='elsif'
  FOR='for'
  ENDFOR='endfor'
  FORM='form'
  ENDFORM='endform'
  IF='if'
  ENDIF='endif'
  IFCHANGED='ifchanged'
  INCREMENT='increment'
  JAVASCRIPT='javascript'
  ENDJAVASCRIPT='endjavascript'
  LAYOUT='layout'
  LIQUID='liquid'
  PAGINATE='paginate'
  ENDPAGINATE='endpaginate'
  RAW='raw'
  ENDRAW='endraw'
  RENDER='render'
  SCHEMA='schema'
  ENDSCHEMA='endschema'
  SECTION='section'
  SECTIONS='sections'
  STYLE='style'
  ENDSTYLE='endstyle'
  STYLESHEET='stylesheet'
  TABLEROW='tablerow'
  ENDTABLEROW='endtablerow'
  UNLESS='unless'
  ENDUNLESS='endunless'
  WHEN='when'

  // Operators
  SET='='
  EQ='=='
  NE='!='
  GT='>'
  LT='<'
  GE='>='
  LE='<='
  OR='or'
  AND='and'
  CONTAINS='contains'
  IN='in'
  BY='by'
  WITH='with'
  AS='as'
  REVERSED='reversed'
  OFFSET='offset'
  LIMIT='limit'
  COLS='cols'

  // Literals & Other
  FALSE='false'
  TRUE='true'
  NIL='nil'
  BLANK='blank'
  EMPTY='empty'

  DOT='.'
  COMMA=','
  COLON=':'
  PIPE='|'
  LPAREN='('
  RPAREN=')'
  LBRACKET='['
  RBRACKET=']'
  RANGE='..'
  HASH='#'

  // Complex tokens
  IDENTIFIER='regexp:[a-zA-Z_][a-zA-Z0-9_-]*'
  NUMBER='regexp:[0-9]+(\.[0-9]+)?'
  STRING_LITERAL="regexp:(\"[^\"]*\"|'[^']*')"
  TEMPLATE_TEXT='regexp:[^\{]+|\{'
]
}

shopifyLiquidFile ::= item*

private item ::= TEMPLATE_TEXT | liquid_tag | liquid_output

liquid_tag ::= (LIQUID_TAG_START | LIQUID_TAG_START_STRIP) tag_content (LIQUID_TAG_END | LIQUID_TAG_END_STRIP)
liquid_output ::= (LIQUID_OUTPUT_START | LIQUID_OUTPUT_START_STRIP) output_content (LIQUID_OUTPUT_END | LIQUID_OUTPUT_END_STRIP)

tag_content ::= (tag_body)?
private tag_body ::=
    assign_tag | break_tag | capture_tag | endcapture_tag | case_tag | endcase_tag |
    comment_tag | endcomment_tag | continue_tag | cycle_tag | decrement_tag |
    echo_tag | else_tag | elsif_tag | for_tag | endfor_tag | form_tag | endform_tag |
    if_tag | endif_tag | ifchanged_tag | increment_tag | javascript_tag |
    endjavascript_tag | layout_tag | liquid_tag_kw | paginate_tag | endpaginate_tag |
    raw_tag | endraw_tag | render_tag | schema_tag | endschema_tag |
    section_tag | sections_tag | style_tag | endstyle_tag | stylesheet_tag |
    tablerow_tag | endtablerow_tag | unless_tag | endunless_tag | when_tag |
    generic_tag

assign_tag ::= ASSIGN IDENTIFIER SET expression
break_tag ::= BREAK
capture_tag ::= CAPTURE IDENTIFIER
endcapture_tag ::= ENDCAPTURE
case_tag ::= CASE variable_lookup
endcase_tag ::= ENDCASE
comment_tag ::= COMMENT (HASH TEMPLATE_TEXT?)?
endcomment_tag ::= ENDCOMMENT
continue_tag ::= CONTINUE
cycle_tag ::= CYCLE (literal (COLON literal)? (COMMA literal)*)
decrement_tag ::= DECREMENT variable_lookup
echo_tag ::= ECHO expression
else_tag ::= ELSE
elsif_tag ::= ELSIF condition
for_tag ::= FOR IDENTIFIER IN (variable_lookup | range_expression) (REVERSED)? (property)*
endfor_tag ::= ENDFOR
form_tag ::= FORM (literal | variable_lookup) (COMMA (literal | variable_lookup))* (property)*
endform_tag ::= ENDFORM
if_tag ::= IF condition
endif_tag ::= ENDIF
ifchanged_tag ::= IFCHANGED
increment_tag ::= INCREMENT variable_lookup
javascript_tag ::= JAVASCRIPT
endjavascript_tag ::= ENDJAVASCRIPT
layout_tag ::= LAYOUT (literal | NIL)
liquid_tag_kw ::= LIQUID
paginate_tag ::= PAGINATE variable_lookup BY NUMBER (property)*
endpaginate_tag ::= ENDPAGINATE
raw_tag ::= RAW
endraw_tag ::= ENDRAW
render_tag ::= RENDER (STRING_LITERAL | variable_lookup) ((FOR | WITH) variable_lookup AS IDENTIFIER | (COMMA property)*)?
schema_tag ::= SCHEMA
endschema_tag ::= ENDSCHEMA
section_tag ::= SECTION (STRING_LITERAL | variable_lookup)
sections_tag ::= SECTIONS (STRING_LITERAL | variable_lookup)
style_tag ::= STYLE
endstyle_tag ::= ENDSTYLE
stylesheet_tag ::= STYLESHEET
tablerow_tag ::= TABLEROW IDENTIFIER IN (variable_lookup | range_expression) (property)*
endtablerow_tag ::= ENDTABLEROW
unless_tag ::= UNLESS condition
endunless_tag ::= ENDUNLESS
when_tag ::= WHEN (value ((OR | COMMA) value)*)

generic_tag ::= IDENTIFIER (parameter | expression)*

condition ::= expression (comparison_operator expression)?
comparison_operator ::= EQ | NE | GT | LT | GE | LE | CONTAINS

parameter ::= IDENTIFIER COLON (literal | variable_lookup) {pin=1}
property ::= IDENTIFIER COLON expression {pin=1 implements="com.intellij.psi.PsiNameIdentifierOwner" methods=[getKey getValue getName setName getNameIdentifier getPresentation]}

output_content ::= expression

expression ::= value (PIPE filter)*
filter ::= IDENTIFIER (COLON filter_arguments)? {implements="com.intellij.psi.PsiNameIdentifierOwner" methods=[getName setName getNameIdentifier]}
filter_arguments ::= arguments (COLON arguments)*
arguments ::= expression (COMMA expression)*

value ::= literal | variable_lookup | range_expression
literal ::= NUMBER | STRING_LITERAL | boolean_literal | NIL | BLANK | EMPTY
boolean_literal ::= TRUE | FALSE

variable_lookup ::= IDENTIFIER (accessor)* {implements="com.intellij.psi.PsiNameIdentifierOwner" methods=[getName setName getNameIdentifier]}
accessor ::= DOT IDENTIFIER | LBRACKET expression RBRACKET

range_expression ::= LPAREN (NUMBER | variable_lookup) RANGE (NUMBER | variable_lookup) RPAREN

keyword ::= ASSIGN | BREAK | CAPTURE | ENDCAPTURE | CASE | ENDCASE | COMMENT | ENDCOMMENT | CONTINUE | CYCLE | DECREMENT | ECHO | ELSE | ELSIF | FOR | ENDFOR | FORM | ENDFORM | IF | ENDIF | IFCHANGED | INCREMENT | JAVASCRIPT | ENDJAVASCRIPT | LAYOUT | LIQUID | PAGINATE | ENDPAGINATE | RAW | ENDRAW | RENDER | SCHEMA | ENDSCHEMA | SECTION | SECTIONS | STYLE | ENDSTYLE | STYLESHEET | TABLEROW | ENDTABLEROW | UNLESS | ENDUNLESS | WHEN | IN | BY | WITH | AS | REVERSED | OFFSET | LIMIT | COLS | OR | AND | CONTAINS | HASH